#!/usr/bin/env bash

# basic project configuration file

# container configuration

export PLATFORM_COMPONENT_NAME="<%= name %>"
export PLATFORM_COMPONENT_EXTERNAL_PORT="<%= port %>"
export HOST_CONTAINER_NAME="${PLATFORM_COMPONENT_NAME}"

# container image config
# > include what you need to define the image (the image is the recipe for the cake)

# image repository details
export HOST_REPOSITORY_ORG="lineage"
export HOST_REPOSITORY_NAME="docker"

export DOCKER_REGISTRY="lineage-linos-docker.jfrog.io"

# image details
#export HOST_IMAGE_NAME="${HOST_REPOSITORY_USERNAME}/${HOST_REPOSITORY_ORG}/${HOST_CONTAINER_NAME}"
export HOST_IMAGE_NAME="${DOCKER_REGISTRY}/${HOST_CONTAINER_NAME}"
export HOST_IMAGE_DESC="REST api container image"
